FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/.core/Core.Messages/Core.Messages.csproj", "src/.core/Core.Messages/"]
COPY ["src/.core/Core.Service.Host.Convention/Core.Service.Host.Convention.csproj", "src/.core/Core.Service.Host.Convention/"]
COPY ["src/.core/Core.Service.Host.ServiceDiscovery.Interfaces/Core.Service.Interfaces.csproj", "src/.core/Core.Service.Host.ServiceDiscovery.Interfaces/"]
COPY ["src/.core/Core.Service.Host.ServiceDiscovery/Core.Service.Host.Client.csproj", "src/.core/Core.Service.Host.ServiceDiscovery/"]
COPY ["src/.core/Core.Service.Host/Core.Service.Host.csproj", "src/.core/Core.Service.Host/"]
COPY ["src/.core/Core.Tool/Core.Tool.csproj", "src/.core/Core.Tool/"]
COPY ["src/services/Exs/Exs.Contract.Service/Exs.Contract.Service.csproj", "src/services/Exs/Exs.Contract.Service/"]
COPY ["src/services/Exs/Exs.Implementation/Exs.Implementation.csproj", "src/services/Exs/Exs.Implementation/"]

RUN dotnet restore "src/services/Exs/Exs.Implementation/Exs.Implementation.csproj"
COPY . .
WORKDIR "/src/src/services/Exs/Exs.Implementation"
RUN dotnet build --no-restore "Exs.Implementation.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]