version: '3.4'

services:
  api-test:
    image: ${FULL_NAME}/api-test
    container_name: ${FULL_NAME}-api-test
    build:
      context: .
      dockerfile: ../src/services/Api/Api.Test/Dockerfile
      labels:
        - app.company=${LOGO}
        - app.name=${APP_NAME}

  svc:
    image: ${FULL_NAME}/svc
    container_name: ${FULL_NAME}-svc
    build:
      context: .
      dockerfile: ../src/services/Svc/Svc.Implementation/Dockerfile
      labels:
        - app.company=${LOGO}
        - app.name=${APP_NAME}

  consul-server:
    image: consul:latest
    container_name: consul-server-get-start
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0' -data-dir=/tmp/consul
    environment: 
      - CONSUL_LOCAL_CONFIG={"datacenter":"east-aws","data_dir":"/opt/consul","log_level":"DEBUG","node_name":"develop","server":true}
    labels:
      - app.company=${LOGO}
      - app.name=${APP_NAME}

  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml:rw
    depends_on:
      - consul-server
    labels:
      - app.company=${LOGO}
      - app.name=${APP_NAME}