version: '3.4'

networks:
  exp-appname:
    driver: bridge

services:
  api-test:
    image: ${DOCKER_REGISTRY}/api-test
    build:
      context: ../
      dockerfile: src/services/Api/Api.Test/Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME}

  exs:
    image: ${DOCKER_REGISTRY}/exs
    build:
      context: ../
      dockerfile: src/services/Exs/Exs.Implementation/Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME} 
