version: '3.4'

networks:
  exp-appname:
    driver: bridge

services:
  api-test:
    image: ${DOCKER_REGISTRY}/api-test
    build:
      context: .
      dockerfile: ../src/services/Api/Api.Test/Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME}

  backend-example:
    image: ${DOCKER_REGISTRY}/backend-example
    build:
      context: .
      dockerfile: ../src/services/Svc/Svc.Implementation/Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME}
