version: '3.4'

services:
  api-test:
    container_name: ${APP_NAME}.api-test
    ports:
      - "33301:80"
    networks:
      exp-appname:

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ApplicationConfig__ApplicationName=${APP_NAME}
      - ServiceConfig__ServiceName=api-test

  backend-example:
    container_name: ${APP_NAME}.backend-example
    ports:
      - "33300:80"
    networks:
      exp-appname:

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ApplicationConfig__ApplicationName=${APP_NAME}
      - ServiceConfig__ServiceName=backend-example

