version: '3.4'

networks:
  exp-appname:
    driver: bridge

services:
  api-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__ReverseProxyAddress=${REVERSE_PROXY_ADDRESS}
      - ServiceConfig__ServiceName=${FULL_NAME}-api-test
      - ServiceConfig__ServiceID=${FULL_NAME}-api-test
      - ServiceConfig__ServiceAddress=http://${FULL_NAME}-api-test:80
      - ServiceConfig__ServiceDiscoveryAddress=http://consul-server-get-start:8500
      - ServiceConfig__Tags__0=traefik.enable=true
      - ServiceConfig__Tags__1=traefik.tags=exposed
      - ServiceConfig__Tags__2=traefik.http.routers.${FULL_NAME}-api-test.rule=Host(`localhost`) && PathPrefix(`/${FULL_NAME}-api-test`)
      - ServiceConfig__Tags__3=traefik.http.middlewares.${FULL_NAME}-api-test-stripprefix.stripprefix.prefixes=/${FULL_NAME}-api-test
      - ServiceConfig__Tags__4=traefik.http.routers.${FULL_NAME}-api-test.middlewares=${FULL_NAME}-api-test-stripprefix@consulcatalog
      - ServiceConfig__Tags__5=traefik.http.routers.${FULL_NAME}-api-test-internal.rule=Host(`reverse-proxy`) && PathPrefix(`/${FULL_NAME}-api-test`)
      - ServiceConfig__Tags__6=traefik.http.middlewares.${FULL_NAME}-api-test-internal-stripprefix.stripprefix.prefixes=/${FULL_NAME}-api-test
      - ServiceConfig__Tags__7=traefik.http.routers.${FULL_NAME}-api-test-internal.middlewares=${FULL_NAME}-api-test-internal-stripprefix@consulcatalog
    ports:
      - "33301:80"
    networks:
      - exp-appname

  svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__ReverseProxyAddress=${REVERSE_PROXY_ADDRESS}
      - ServiceConfig__ServiceName=${FULL_NAME}-svc
      - ServiceConfig__ServiceID=${FULL_NAME}-svc
      - ServiceConfig__ServiceAddress=http://${FULL_NAME}-svc:80
      - ServiceConfig__ServiceDiscoveryAddress=http://consul-server-get-start:8500
      - ServiceConfig__Tags__0=traefik.enable=true
      - ServiceConfig__Tags__1=traefik.tags=exposed
      - ServiceConfig__Tags__2=traefik.http.routers.${FULL_NAME}-svc.rule=Host(`localhost`) && PathPrefix(`/${FULL_NAME}-svc`)
      - ServiceConfig__Tags__3=traefik.http.middlewares.${FULL_NAME}-svc-stripprefix.stripprefix.prefixes=/${FULL_NAME}-svc
      - ServiceConfig__Tags__4=traefik.http.routers.${FULL_NAME}-svc.middlewares=${FULL_NAME}-svc-stripprefix@consulcatalog
      - ServiceConfig__Tags__5=traefik.http.routers.${FULL_NAME}-svc-internal.rule=Host(`reverse-proxy`) && PathPrefix(`/${FULL_NAME}-svc`)
      - ServiceConfig__Tags__6=traefik.http.middlewares.${FULL_NAME}-svc-internal-stripprefix.stripprefix.prefixes=/${FULL_NAME}-svc
      - ServiceConfig__Tags__7=traefik.http.routers.${FULL_NAME}-svc-internal.middlewares=${FULL_NAME}-svc-internal-stripprefix@consulcatalog
    ports:
      - "33300:80"
    networks:
      - exp-appname

  consul-server:
    ports:
      - "8500:8500"
    networks:
      exp-appname:

  reverse-proxy:
    ports:
      - "33398:8080"
      - "33399:5001"
    networks:
      exp-appname:

