version: '3.4'

services:

  api.gw:
    image: ${LOGO}-${APP_NAME}-api-gw/${APP_VERSION}
    container_name: ${LOGO}-${APP_NAME}-api-gw
    build:
      context: .
      dockerfile: Api.Gw/Dockerfile
      labels:
        - app.company=${LOGO}
        - app.name=${APP_NAME}
    networks:
      - pet-network



  consul-server:
    image: consul:latest
    container_name: consul-server-get-start
    ports:
      - "8500:8500"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0' -data-dir=/tmp/consul
    environment: 
      - CONSUL_LOCAL_CONFIG={"datacenter":"east-aws","data_dir":"/opt/consul","log_level":"DEBUG","node_name":"develop","server":true}
    networks:
      pet-network:



  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    ports:
      - "33398:8080"
      - "33399:5001"
    volumes:
      - ./.dev-env/traefik.toml:/etc/traefik/traefik.toml:rw
    depends_on:
      - consul-server
    networks:
      - pet-network




networks:
  pet-network:
    ipam:
      driver: default
