[entryPoints]
  [entryPoints.http]
  address = ":5001"

[api]
  debug = true
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"

################################################################
# Consul Catalog Provider
################################################################

# Enable Consul Catalog configuration backend
[providers.consulCatalog]

refreshInterval = "30s"
exposedByDefault = false
prefix = "traefik"

[providers.consulCatalog.endpoint]

address = "exp-consul-server:8500"
scheme = "http"
endpointWaitTime = "15s"