version: '3.4'

networks:
  exp-appname:
    driver: bridge

services:
  api-test:
    image: ${DOCKER_REGISTRY}/${APP_NAME}.api-test:${APP_VERSION}
    build:
      context: ../
      dockerfile: src/services/Api/Api.Test/${Configuration}.Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME}

  exs:
    image: ${DOCKER_REGISTRY}/${APP_NAME}.exs:${APP_VERSION}
    build:
      context: ../
      dockerfile: src/services/Exs/Exs.Implementation/${Configuration}.Dockerfile
      labels:
        - app.logo=${LOGO}
        - app.name=${APP_NAME} 
